#!/bin/bash

# ==========================================
# ONE-SHOT HOSTNAME RANDOMIZER INSTALLER
# ==========================================

#################### ONLY CHANGE THE PARAMETERS BETWEEN THESE HASH MARKS IF YOU NEED A CUSTOM HOSTNAME PREFIX ####################
# Configuration
DEFAULT_PREFIX="GL-1800"
##################################################################################################################################


PREFIX="${1:-$DEFAULT_PREFIX}"
SCRIPT_PATH="/usr/local/bin/randomize-hostname.sh"
SERVICE_PATH="/etc/systemd/system/randomize-hostname.service"

if [[ $EUID -ne 0 ]]; then
   echo "[!] Error: Please run with sudo." 
   exit 1
fi

echo "[*] Setting up hostname randomizer with prefix: $PREFIX"

# 1. Create the worker script
cat << 'EOF' > "$SCRIPT_PATH"
#!/bin/bash
# Generated by install-randomizer.sh
PREFIX_VAL="REPLACE_ME_PREFIX"
RANDOM_HEX=$(head -c 2 /dev/urandom | xargs printf '%02x')
NEW_HOST="${PREFIX_VAL}-${RANDOM_HEX}"

hostnamectl set-hostname "$NEW_HOST"
sed -i "s/127.0.1.1.*/127.0.1.1\t$NEW_HOST/g" /etc/hosts
echo "[+] Hostname set to: $NEW_HOST"
EOF

# Inject the chosen prefix into the worker script
sed -i "s/REPLACE_ME_PREFIX/$PREFIX/g" "$SCRIPT_PATH"
chmod +x "$SCRIPT_PATH"

# 2. Create the Systemd Service
cat << EOF > "$SERVICE_PATH"
[Unit]
Description=Randomize Hostname on Boot
After=local-fs.target
DefaultDependencies=no

[Service]
Type=oneshot
ExecStart=$SCRIPT_PATH
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target
EOF

# 3. Enable and Run
systemctl daemon-reload
systemctl enable randomize-hostname.service
bash "$SCRIPT_PATH" # Run it now for immediate effect

echo "---"
echo "[+] Installation complete."
echo "[+] Your hostname will now change automatically on every boot."
echo "[*] Current Hostname: $(hostname)"
